---
title: "Task 2 - Cake ingredients - Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

cake_data <- read_csv(here("clean_data/clean_cake.csv"))
```


Which cake has the most cocoa in it?

```{r}
cake_data %>% 
  filter(ingredient == "Cocoa") %>% 
  arrange(desc(values)) %>% 
  head(1)
```

For sponge cake, how many cups of ingredients are used in total?

```{r}
# Filter for any ingredients that list cup as measure, and for the Sponge cake
# Then drops any NA values (as these signify that the ingredient is not used)
# Then sums the cup values of whatever is left
cake_data %>%
  filter(measure == "cup", cake == "Sponge") %>%
  drop_na(values) %>%
  summarise(total_cups = (sum(values)))
 
```


How many ingredients are measured in teaspoons?

```{r}
# This groups by whatever the measure for each ingredient is, filters for teaspoon
# then lists all the ingredients that have this measure, then counts how many are returned
cake_data %>% 
  group_by(measure) %>% 
  filter(measure == "teaspoon") %>% 
  summarise(unique(ingredient)) %>% 
  count()
```

Which cake has the most unique ingredients?

```{r}
# this groups by cake, counts each time it appears in the list (which signifies how many ingredients are used)
# then returns whichever cake has the highest total
drop_na(cake_data) %>% 
  group_by(cake) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  head(1)
```


Which ingredients are used only once?

```{r}
# this groups by ingredient, counts how many times each one appears, then returns ingredients that only appear once
drop_na(cake_data) %>% 
  group_by(ingredient) %>% 
  arrange(ingredient) %>% 
  count() %>% 
  filter(n == 1)
```

